services:
  backend:
    build:
      context: ./backend/django
      dockerfile: Dockerfile
    image: philgeps-backend:latest
    ports:
      - "3200:8000"
    environment:
      SECRET_KEY: "your-secret-key"
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1,philgeps-api.simple-systems.dev,philgeps.simple-systems.dev"
      CORS_ALLOWED_ORIGINS: "https://philgeps.simple-systems.dev"
      CSRF_TRUSTED_ORIGINS: "https://philgeps.simple-systems.dev"
      PARQUET_DIR: "/data/parquet"
    # volumes:
    #   - ./backend/django/static_data:/data/parquet

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://philgeps-api.simple-systems.dev
    image: philgeps-frontend:latest
    ports:
      - "3000:80"
      
  # Optional: Use this if you want to run cloudflared in Docker instead of as a background service
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run
  #   environment:
  #     TUNNEL_TOKEN: "<your-cloudflare-tunnel-token>"
  #   depends_on:
  #     - backend
  #     - frontend
