version: '3.8'
services:
  backend:
    image: philgeps-backend:latest
    ports:
      - "3200:8000"
    environment:
      SECRET_KEY: "your-secret-key"
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1,philgeps-api.simple-systems.dev"
      CORS_ALLOWED_ORIGINS: "https://philgeps.simple-systems.dev"
      CSRF_TRUSTED_ORIGINS: "https://philgeps.simple-systems.dev"
      PARQUET_DIR: "/data/parquet"
    # volumes:
    #   - ./backend/django/static_data:/data/parquet

  frontend:
    image: philgeps-frontend:latest
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: "https://philgeps-api.simple-systems.dev"